theme = "everforest_dark"

[editor]
mouse = false
rulers = [80]
true-color = true
color-modes = true
shell = ["sh", "-c"]
bufferline = "always"
line-number = "relative"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 1

[editor.whitespace.render]
newline = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
Z.Q = ":quit!"
Z.Z = ":write-quit!"
tab = "goto_next_buffer"
space.q = ":buffer-close"
S-tab = "goto_previous_buffer"
space.m = ':! mdview "%{buffer_name}"'
a = ["append_mode", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" }
